### ISSUE TITLE
enable temporarily hiding of languages

### ISSUE THREAD

**Issue by muellert** [plone/plone.app.multilingual#109]
I want to add a language, do the translations, then bulk go-live with that. But until ready, the new language should be hidden, instead of delivering the wrong content (if any).

This could probably be implemented by making the language selector widget respect the visibility of the top-level language folders and show the language only if the top-level folder is in the "published" state (or in one of a list of eligible states).

Currently, as soon as you configure a language, it appears in the language selector, regardless of content availability, but without configuring a language, one cannot translate to it.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue
