### ISSUE TITLE
Migration tab missing when LinguaPlone is installed in parallel

### ISSUE THREAD

**Issue by cburghardt** [plone/plone.app.multilingual#110]
This is plone 4.3.2 and plone.app.multilingual 1.2.1
I have an existing LinguaPlone site and want to switch to PAM in order to get multilanguage support for an existing Dexterity type.
I have installed the products but no language folders are created. I have selected German as default language and English as translatable in the language control panel. There is no migration tab.
I also get the following error on my german startpage:
ERROR plone.app.viewletmanager rendering of plone.contentviews in plone.contentactions fails: ('Could not adapt', <PloneSite at /special>, <InterfaceClass plone.multilingual.interfaces.ITranslationManager>)

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue
