### ISSUE TITLE
Exception when LinguaPlone is removed

### ISSUE THREAD

**Issue by cburghardt** [plone/plone.app.multilingual#114]
I have migrated my LinguaPlone site to plone.app.multilingual so executed the steps 1 and 2. If I remove LinguaPlone from my buildout my site does not come up anymore:

TypeError: ('object.**new**(SyncedLanguages) is not safe, use Persistence.Persistent.**new**()', <function _reconstructor at 0x7f031add6c08>, (<class 'Products.LinguaPlone.vocabulary.SyncedLanguages'>, <type 'object'>, None))

**Comment by mbarde** [comment]
Following this steps worked for me:  https://docs.plone.org/4/en/develop/plone/i18n/translating_content.html#switching-from-linguaplone
