### ISSUE TITLE
Editing is no longer possible

### ISSUE THREAD

**Issue by cburghardt** [plone/plone.app.multilingual#115]
I have migrated my LinguaPlone website to PAM (after code corrections steps 1 and 2 could be executed as described in #110 but the last step can not be executed as noted in #114). The language folders have been setup and all content is translated and associated correctly. Unfortunately I can not edit any translated content anymore. I can view the page but as soon as I click on the edit button I just get a page not found error. I can still edit the "original" content so german in my case.
Any help would be highly appreciated!

**Comment by jensens** [comment]
probably outdated
