### ISSUE TITLE
Uploading image from TinyMCE while translating a content in babel view links the uploaded image as the translation

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.multilingual#116]
After discussing with @bloodbare, this should be fixed by adding a hidden field into (or other marker) into babel add form so that the correct ObjectCreatedEvent is recognized by inspecting the request.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue
