### ISSUE TITLE
plone.app.multilingual should not require the use of sessions

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.multilingual#120]
Dylan Jay wrote: "I don't know much about p.a.multilingual but I do know that nothing in plone core currently depends on sessions and this is something that some people rely on. Not having to implement replicated sessions between redundant servers can help you avoid some headaches for example. Requiring use of sessions in a major plugin or core would be a big change IMO"

**Comment by agitator** [comment]
+10

**Comment by bloodbare** [comment]
I'm agree, do you find a way to know from which language/object are you comming to create ++add++ objects on the fly ? I only saw the option to create a hidden z3cwidget that hosts where it comes from and add it to all Translatable objects, I thought its more nasty than using sessions. @djay

**Comment by datakurre** [comment]
@bloodbare I added the z3cform fields, but agreed that they are not a good solution, and not even a complete one.

I guess, the easiest would be to make ++add++ traversal to include all the data.

**Comment by bloodbare** [comment]
Agree, ++add++contenttypes/UID-ORIG ?

**Comment by datakurre** [comment]
Languages can be interpreted from the contextes? (Just wondering, why the language was stored in the session...)

Maybe a custom traverse namespace instead of ++add++ (=no overrides), but it could use ++add++ internally to look up the add form. Just checked that DX add forms should not override the form action URL, but use request.getURL, so user should stay in our namespace until content is created (or creation cancelled).

**Comment by bloodbare** [comment]
The two params should be Translation group and original language, the destination language can be aquired from the context!

I thought first to use a custom adapter (++translate++) but I don't remember why I refused that idea. It should work.

**Comment by jensens** [comment]
I would go for ``TARGETFOLDER/++addtranslation++SOURCEUID``. 
So we can derive language (source/target) from target context and source uid. 

Pros:
- simple readable url
- minimal additional information passed. 
- neither session nor cookies needed.

Cons:
- not stateless
- needs read access on source (needed anyway if language independent fields are used).

**Comment by jensens** [comment]
I started a branch here https://github.com/plone/plone.app.multilingual/tree/issue-120-remove-session - just FYI, WIP

**Comment by datakurre** [comment]
I'm working on this, but the first version will disable connection of translations without babel view.

Currently, ++addtranslation++ -traverser is only used when babel view is enabled. When babel view is disabled, ``create_translation`` uses ``createObject``-dispatcher.

**Comment by jensens** [comment]
hmm, this should be changed, so createTranslation can use the traverser as well, but with a different view.

**Comment by datakurre** [comment]
@jensens You are correct. Let's see, how far I get. There must be some nasty trap at the end, where the eventual translation connection should be done...

**Comment by saily** [comment]
hi guys, ping me if you need my help here.

**Comment by datakurre** [comment]
@saily @jensens I'm currently fixing tests for this. One issue:

Test users come as anonymous to ++addtranslation++ -traverser and therefore I must use unrestricted portal catalog API instead of the normal restricted API. Does that make sense? It's hard to remember when users are authenticated and when not :)
