### ISSUE TITLE
List translations that might need to be updated

### ISSUE THREAD

**Issue by khink** [plone/plone.app.multilingual#122]
When one translation of an item changes, it might be necessary to updated all translations accordingly. For example, we have an English page describing a company's services. This page, en/services, is updated: an extra service is added. Now this new service should also be added to ca/serveis and de/dienstleistungen. 

A special case of this is when one language is the "main language", or the "source". Whenever this is updated, other languages should be marked in some manner as needing update, or review at least. P.a.m has no "canonical" object, so this might require some thought to implement, if possible at all.  

With two or three languages, or just a couple of changed pages, this is relatively easy to keep track of. When there's five or more languages, or more than 20 pages, i'd say we might benefit from having a structured approach for this.

Note: I don't have this use case yet, i'm just writing this down because i think it might make Plone's multilingual story better.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue
