### ISSUE TITLE
Defining languages on LRF creates language folder inside the LRF

### ISSUE THREAD

**Issue by bloodbare** [plone/plone.app.multilingual#125]
Because of the acquisition the LRF is created inside the Language Root Folder instead of the root when you define a new language on the control panel.

**Comment by jensens** [comment]
Outdated?

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
