### ISSUE TITLE
Make calendar and events viewlet work when events are shared 

### ISSUE THREAD

**Issue by dblas** [plone/plone.app.multilingual#127]
When events are shared (because a date is a date in every language even if the comments are specific) calendar as well as events viewlet are unable to see them.
They only see'em when the current folder is the shared one.
But, at the same time, an event collection created for a particular language is able to see the events even if they are stored in the shared language part of the site.

It's a matter of starting point of searching I suppose (I don't want to read the code at this moment).
More generally speaking, it asks about the way such lookups should be carried out: why not doing the same thing about news viewlet (current language + shared language) as well as any new viewlet that could appear?

db

**Comment by jensens** [comment]
so are you talking about making fields language-independent?
there is already a lot of work done at plone.app.event here:
plone/plone.app.event#170

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
