### ISSUE TITLE
Searching content is limited to language root folder

### ISSUE THREAD

**Issue by skillfully** [plone/plone.app.multilingual#134]
using Plone v4.1.6 & pas v1.2.1
Searching content with internal plone-search from any language folder e.g. /de/foo only responses with content from this language folder. Shared content is not included in the searchresults. The plone-search uses an url for search requests created from navigation_root_url per default.

**Comment by jensens** [comment]
@datakurre is this still true with your new implementation?

**Comment by datakurre** [comment]
@jensens I'm not quite familiar with PAM 1.x, but this has always been working in PAM 2.x and also with the new shared folder implementation. The new shared folder uses the same approach as the original PAM 2.0, which is to index shared content once for each language.

**Comment by jensens** [comment]
i am pretty sure this works with the latest version of pam
