### ISSUE TITLE
CI integration broken?

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.multilingual#146]
I cant find any running CI integration running: Travis is disabled and on jenkins last run was April 2014.

Is this intended?

I'd like to see it running at least with Plone 4.3 latest and latest 5 dev.

**Comment by djowett** [comment]
@jensens Travis is obviously enabled now.

**Comment by gforcada** [comment]
@jensens what do you mean last run on Jenkins at April 2014? AFAIK for Plone 5 is already integrated into buildout.coredev, isn't it?

**Comment by djowett** [comment]
@gforcada note that this is nearly a year old 
- I just thought it might be able to be closed

**Comment by gforcada** [comment]
Oh thanks, I didn't notice that :oops: let's close and let him reopen if not.
