### ISSUE TITLE
start_neutral in PloneLanguageTool makes no sense in LIF concept.

### ISSUE THREAD

**Issue by saily** [plone/plone.app.multilingual#148]
I discovered many failing tests in `archetypes.multilingual` during the Alpine City Sprint. When we build up the CMFPlone controlpanel for PAM we have to remove the `start_neutral` flag if PAM is activated.

**Comment by saily** [comment]
1. neutral document created in a folder
2. `set_recursive_language` sets the language on the new document
3. document is not language independent at all. 

-- 

if we move a document into LIF folder, we have to change the language back to language independent.

**Comment by datakurre** [comment]
I agree. With PAM

* content directly under root could still be neutral, but those are rare (Members-folder is)
* all content under Language Root Folder make only sense with language
* all content under Language independent make only sense without language

I assume the missing piece here is to set_recursive_language_independent when document is moved to LIF folder.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
