### ISSUE TITLE
"Migration" from Single language  site seems to be missing on 2.x

### ISSUE THREAD

**Issue by djowett** [plone/plone.app.multilingual#151]
...no Language Shared folder created & nothing is moved into en or de folders (except copy_of_Members - which of course is not desirable.  This did work for me in 1.x, but now I'm trialing v2.0a3 & the above occurs.  I don't know whether this is strictly "migration", but I couldn't find any docs on moving data apart from Migrate from LinguaPlone.  Does this scenario have a test case?

**Comment by djowett** [comment]
Hmm, I've just searched for the same problem and found my own issue :-( 

I note that there is no use (or even reference) of `IInitialCleanSiteSetupAdapter` in 2.x - it seems there is a bit of code just missing here.

@bsuttor did you encounter this?

**Comment by bsuttor** [comment]
Sorry but I don't remember problems with IInitialCleanSiteSetupAdapter, but I didn't migrate LinguaPlone contents, only Plone "standard" archetypes contents.

**Comment by djowett** [comment]
@bsuttor thanks for the reply.

I think IInitialCleanSiteSetupAdapter is a red herring.

I am also coming in with single language Plone contents, but in plone.app.contenttypes.  But running migration steps, leaves my folder contents emptied into the root folder, not nicely put into the default languages LRF as I would have expected/hoped.  Was p.a.m. nicer to you when you ran the migration steps?

**Comment by djowett** [comment]
Having looked through git history I found that 
* CleanSite Setup was added by @sneridagh  in Jan 2013
* Cleansite Setup was lost when @bloodbare moved to 2.0  in Sep 2013

I'm not grouching here, but could you both  ( @sneridagh and @bloodbare) just say whether you think this Clean Site Setup should be reinstated in 2.x?  I'm willing to give it a go myself...

**Comment by bloodbare** [comment]
Hey, quite easy reason we removed because people was not understanding the usage of the two checkbox.
After a discussion with some other p.a.m. users they thought that it was confussing people.

**Comment by djowett** [comment]
@bloodbare thanks for the reply, but does this not mean there is no way to move a single language site to a multilingual site in pam 2.x?  (unless the intention is to install pam 1.x first & upgrade?)

**Comment by bloodbare** [comment]
using folder contens you can move all the content from the root that needs to be moved to a language root folder, the subscribers are supposed to take care that all content is set to the language root folder language. I know its manual but its a task that can be done TTW.

**Comment by djowett** [comment]
@bloodbare OK, that works for me manually - but that needs documenting somewhere (not sure whetehr language control panel or README.rst is best).  
Also IInitialCleanSiteSetupAdapter is therefore redundant & can be removed, right?

Note that the absence of LRF folders in the site root is a fairly reliable sign that a user is migrating from a single language site.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
