### ISSUE TITLE
make "always_show_selector" available via control panel

### ISSUE THREAD

**Issue by simahawk** [plone/plone.app.multilingual#157]
The control panel has the option for cookie override. Description states:

```
Use cookie for manual override. (Required for the language selector viewlet to be rendered.)
```

I wonder why is that? I mean: you can still want to change the language using the selector even if you don't use a cookie.

I discovered there's a property in language tool that bypass any other check and shows the lang selector anyway: `always_show_selector`.

I tested it in combo w/ cookie override disabled and it's working... Can we make it available in the control panel? I can work on this.

**Comment by laulaz** [comment]
It is now available 👍
