### ISSUE TITLE
ImportError: cannot import name ILanguage

### ISSUE THREAD

**Issue by mistub70** [plone/plone.app.multilingual#168]
Hi

My Plone Version:
--------------------------
Plone 4.3.4.1 (4309)
CMF 2.2.8
Zope 2.13.22
Python 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
PIL 2.6.1 (Pillow)

After buildout and restarting the instance I get:
ImportError: cannot import name ILanguage

Kind regards
Michael

**Comment by mistub70** [comment]
btw:
ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/plone.app.multilingual-3.0.3-py2.7.egg/plone/app/multilingual/upgrades.zcml", line 6.2-13.8

**Comment by tomgross** [comment]
According to your error snippet you are using p.a.multilingual 3.0.3 but according to the documentation you should stay with p.a.multilingual < 3.x together with Plone 4.x

    1.x - Plone 4.x with Archetypes and Dexterity
    2.x - Plone >= 4.x, < 5.0 with plone.app.contenttypes (Dexterity) and real shared content
    3.x - Plone >= 5.x

Reopen if this issue persists with p.a.mulilingual 2.x.
