### ISSUE TITLE
Type Name not found (plone.app.multilingual 2.0.1 + plone 4.3.6)

### ISSUE THREAD

**Issue by mistub70** [plone/plone.app.multilingual#169]
Hi all

My Versions:
Plone 4.3.6 (4310)
CMF 2.2.9
Zope 2.13.22
Python 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
PIL 2.6.1 (Pillow)
plone.app.multilingual 2.0.1
archetypes.multilingual 2.0

Added french to the german default language, then added a german site. For this site clicking on "Translate/Create French" generates the error:

Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module archetypes.multilingual.browser.add, line 26, in __call__
KeyError: 'Type name not found: 9adc6a3d1987423e9a23fdf90422aa5b.'

What did I wrong?

Kind regards
Michael

**Comment by mck9** [comment]
Same here.

**Comment by jensens** [comment]
probably an ``archetypes.multilingual`` bug.

**Comment by naro** [comment]
It seems to be more a p.a.multilingual bug
 * The translation form passes an UUID https://github.com/plone/plone.app.multilingual/blob/2.x/src/plone/app/multilingual/browser/translate.py#L86
 * The add view really considers it as UUID https://github.com/plone/plone.app.multilingual/blob/2.x/src/plone/app/multilingual/browser/add.py#L54
 * But finally the UUID is passed as a type parameter to AT adapter (view) https://github.com/plone/plone.app.multilingual/blob/2.x/src/plone/app/multilingual/browser/add.py#L74 - it should pass through the source.portal_type instead.

**Comment by naro** [comment]
This is fixed on https://github.com/plone/plone.app.multilingual/pull/178
