### ISSUE TITLE
New Dexterity content types does not appear in the portal.globalnav

### ISSUE THREAD

**Issue by danielhz** [plone/plone.app.multilingual#174]
I defined some new content types using Dexterity in an add-on created using mr.bob. However, if I use this content types inside a Plone 4.3.6 site that use plone.app.multilingual 2.0.0, then they are not displayed in the portal-globalnav. This issue does not occur in a site that does not use the plone.app.multilingual add-on.

I upload a code that reproduce the first issue in https://github.com/danielhz/degu.issue001.

**Comment by rebelx** [comment]
Any progress on this issue? It is becoming extremely critical for a site that I am developing. Any directions on how to tackle this problem would be highly appreciated.

**Comment by gforcada** [comment]
@rebelx adding a pdb where the portal-globalnav looks for content types and look what restrictions and/or query it does that filters out your content type for example as a starter.

On Plone 5 for example new content types are not, by default globally available, you have to mark them as such, maybe that's the problem?

**Comment by datakurre** [comment]
I confirmed that new content types need to be manually added into "Displayed content types" in "Navigation settings".
