### ISSUE TITLE
multilingual-map not working

### ISSUE THREAD

**Issue by pbauer** [plone/plone.app.multilingual#175]
In Plone 5 Coredev.
Steps to reproduce:
- Create fresh site
- install p.a.m. and enable 2 languages
- create some content
- go to http://localhost:8080/Plone/multilingual-map

You see something useless like:
```
    cfef9c50c1fa4c66bc637c6cac7b3e22
        Missing languages: en
        Translations: /Plone/de/media de
    eda2df0b2d8f4ab19779470b09379bbe
        Missing languages: de
        Translations: /Plone/en/media en
    bfbd96731f504cb289a044c18927cdbf
        Missing languages: en
        Translations: /Plone/de/a-page de
```
There is neither a traceback nor a js-error.

**Comment by bloodbare** [comment]
@pbauer  can you try again, you should see the map tree and the option of missing translations showing the ugly list, I could not find a way to define this list, maybe we should export a csv.

**Comment by pbauer** [comment]
I fixed this in https://github.com/plone/plone.app.multilingual/commit/e88b3e17b16c40d3d4a1ab798f8230f4f98cc5ad and forgot to close the ticket.

**Comment by pbauer** [comment]
@bloodbare for the csv-export you could create a new ticket.
