### ISSUE TITLE
language independent fields shown in translation view when plone.autoform.directives.widget is used

### ISSUE THREAD

**Issue by frisi** [plone/plone.app.multilingual#177]
using plone 4.3.6, plone.app.multilingual 2.x, plone.app.widgets 1.8.0

using the directive `plone.app.multilingual.dx.directives.languageindependent` to mark language independent fields in the schema of my dexterity type works fine.
if i add plone.app.widgets to the mix, the widget (for the topics field in the example below) is editable in translations too, whereas the field `street` is grayed out and not editable.

![multilingual](https://cloud.githubusercontent.com/assets/1120517/9452447/845c9bc0-4ab4-11e5-9c7a-c8e36b73876b.png)

any hints what's wrong or missing to make the topics field not editable in bable-view too?

``` python
from plone.autoform import directives as form
from plone.app.widgets.dx import SelectWidget
from plone.supermodel import model
from zope import schema

class IOrganization(model.Schema):

    languageindependent('street')
    street = schema.TextLine(
        title=_(u'street-label', default=u"Street"),
        required=True,
    )

    form.widget('topics', SelectWidget, multiple='multiple', size=5)
    languageindependent('topics')
    # XXX languageindependent not working in combination with selectwidget from p.a.widgets
    topics = schema.Set(
        title=_('topics-label', default=u"topics"),
        value_type=schema.Choice(
            title=u"Topics",
            vocabulary='yapp.topics',
            ),
        required=True,
    )

```

**Comment by frisi** [comment]
did some additional investigation: the `languageindependent` class is not set on the field in the rendered form. if i'd add it manually (firebug) the input is grayed out properly:

```
<div class="select2-container select2-container-multi pat-select2 languageindependent" id="s2id_autogen1">
...
```

`plone.app.multilingual.browser.add.MultilingualAddForm._process_language_independent` correctly identifies the field as ILanguageIndependentField and the widget `.addClass` is called on is the plone.app.widgets widget already:
```
>>> widgets['topics']
<SelectWidget 'form.widgets.topics'>
>>> type(widgets['topics'])
<class 'plone.app.widgets.dx.SelectWidget'>
```

however, for some reason the class does not end up in the rendered addform.

**Comment by datakurre** [comment]
Thanks for the in-depth investigation. Should really help, when someone tries to fix this.

**Comment by sandros87** [comment]
I'm having the same problem, anyone who tried to fix it came out with a solution?

**Comment by datakurre** [comment]
That may also be a bug in the widget code (not actually in p.a.m. code).

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
