### ISSUE TITLE
IMultilinguaSettings - unremoved registry entries

### ISSUE THREAD

**Issue by skillfully** [plone/plone.app.multilingual#179]
using Plone 4.3.3 with pam 1.2.2 upgraded from an earlier version

Starting the plone instance produces following error:
`WARNING OFS.Uninstalled Could not import class 'IMultilinguaSettings' from module 'plone.app.multilingual.interfaces'`
With commit bafde5128b526a7a37c4b6674c91e51be8480513 this interface was removed from source code, but the settings are still present in registry.
Please provide a cleanup profile or some steps to get rid of this warning and to clean up the registry.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
