### ISSUE TITLE
Google Translate button is shown even when no translation key in settings

### ISSUE THREAD

**Issue by djowett** [plone/plone.app.multilingual#184]
this seems to be because the check doesn't test for None.  The test in BabelUtils looks correct, those in add.py & edit.py are not.

**Comment by djowett** [comment]
Resolved for 1.x by #185.
Couldn't reproduce for 2.x so it seems not to be an issue there.

**Comment by djowett** [comment]
Actually reproduced in 2.x after all.
Can anyone check in master (I'm not yet working in Plone 5.0)

**Comment by jensens** [comment]
Needs check (and fix) if this is true for master part of Plone 5.0.

**Comment by djowett** [comment]
This is also an issue in PAM master /  Plone 5
