### ISSUE TITLE
Clarify naming of Language independent folders

### ISSUE THREAD

**Issue by djowett** [plone/plone.app.multilingual#196]
There's a lack of clarity on this feature in 2.x & master, mostly (IMO) because of the variety of names it has been given, including:
- Neutral root folder (title of the section in Readme.rst)
- language neutral folder (also mentioned in Readme.rst)
- language independent folder (the name of the FTI type, only visible in ZMI & code I think)
- lif (abbreviation of the above, which unfortunately clashes with "Language Independent Field", but fortunately only visible in code)
- Language shared (name of the folder according to Readme.rst)
- Media (_real_ name of the folder in 2.x)
- "shared folder" (how it is referenced in translate menu)

So may I humbly suggest, 
1. the primary stakeholders decide on **one** name to use going forward?
2. can we change Readme.rst accordingly.

@bloodbare @saily @datakurre @sneridagh @jensens and anyone else?

It's not my place (as a minor contributor) to select which name should be used, but I've put a rewrite of the "Neutral root folder" section in Readme.rst as how I think best supposing that you selected "language neutral folder".   (Note I'm currently using 2.x, so tweaks _might_ be required to the below for master (though I think not).  

> ## The "Media" folder - a shared "language neutral folder"
> 
> The root language folders are used to house the content tree for the corresponding language.  However, there are some use cases where we need content that does not belong to any language. For example, for assets or side resources like images, videos and documents. For this reason PAM supplies a special **language neutral folder** to house these kind of objects. After PAM setup, there is a special folder called "Media", which can be accessed through the "Go to shared folder" item of the "Translate" menu. All items placed in this folder will have neutral as their default language and will be visible from the other root language folders as if they were placed there as well.  
> **Note:** _Language Neutral Folder_'s have also been historically known as "Neutral root folder", "language independent folder" and "language shared (folder)"

**Comment by jensens** [comment]
+1 for a unified language.

I would vote for "language independent folder" or "language neutral folder" - for me both are equal good.

**Comment by saily** [comment]
+1 for **Language Independent Folder** or as @datakurre is calling them **LIF**. 
I think - since we also had a lif-branch when implementing this - this is more clear to the core team.

(and btw: `language neutral field` is also in conflict with `language neutral folder`)

**Comment by datakurre** [comment]
Daniel Widerin wrote:
> +1 for *Language Independent Folder* or as @datakurre 
> <https://github.com/datakurre> is calling them *LIF*.
> I think - since we also had a lif-branch when implementing this - this 
> is more clear to the core team.
>
> (and btw: |language neutral field| is also in conflict with |language 
> neutral folder|)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/plone/plone.app.multilingual/issues/196#issuecomment-159937881>.
>

FWIW I called them LIF, because there was already LangaugeIndependentField and LRF (LanguageRootFolder).

**Comment by djowett** [comment]
Thanks for replies so far.
I'd say we should choose "Language Independent Folder" over "LIF" - because users could confuse LIF with Language Independent Field

**Comment by djowett** [comment]
@datakurre is that a vote for LIF?

Any more votes from anyone? @mauritsvanrees @gforcada would you like to say?
Anyone else we should ask?

**Comment by datakurre** [comment]
I'm indifferent. LRF and LIF and LanguageIndependentField are technical terms used in the current codebase. In documentation they could be whatever is easier to understand. +1 for fixing all docs to use the same terms. Whicever is being choosed.

**Comment by mauritsvanrees** [comment]
I don't mind much, but I'm happy with "language independent folder".

**Comment by gforcada** [comment]
@djowett flip a coin and go for it, once the documentation is updated and consistent it will be a matter of search and replace if we change our minds ;-) or to put it another way: don't get the [analysis paralysis](https://en.wikipedia.org/wiki/Analysis_paralysis)

**Comment by djowett** [comment]
"language independent folder" it is then 

( @gforcada my coin didn't have that many sides)

**Comment by djowett** [comment]
I found I only needed to change README.rst

**Comment by djowett** [comment]
This did also need a change in the relevant Menu Item.
