### ISSUE TITLE
When translating a page the portal message doesn't replace language fields

### ISSUE THREAD

**Issue by djowett** [plone/plone.app.multilingual#202]
![add-form-is-translation-error](https://cloud.githubusercontent.com/assets/1470021/11597157/c17be4a0-9ab1-11e5-8f80-aa1e042f366a.png)

This is on Plone 4.3.2, PAM 2.x, using plone.app.contenttypes 1.1b6.
In this instance I was translating a Page, Folders seem to work slightly better.

Looking at [the template](https://github.com/plone/plone.app.multilingual/blob/2.x/src/plone/app/multilingual/browser/templates/add-form-is-translation.pt), I note a few things (which I believe equally apply to 3.x / master):
1. There is a message "If you want to create this object without being a translation press" which is in the span nested within the dd block - yet both the dd & the span have `i18n:translate=` set... I can't see that working, as surely the whole dd block contents are replaced by it's translate string (indeed "If you want..." is obviously _not_ in the Portal Message above)
2. Actually translating the [whole dd block](https://github.com/plone/plone.app.multilingual/blob/2.x/src/plone/app/multilingual/locales/plone.app.multilingual.pot#L121) is unnecessary.  We can just translate the part before the `<ul>` tag, and the span at the bottom, which simplifies things quite a bit.
3. What's this `<span>x</span>` thing meant to be/do?

Can someone confirm I'm thinking clearly on this?
Is it complicated to replace a string/template part with an established translation??

**Comment by djowett** [comment]
@fredvd @mauritsvanrees can I get your thoughts on this?  
As it seems to be a repeat of #80 

particularly note point 1, that is (IMO) the i18n:translate attribute effectively overwrites nearly half the page template, and therefore what we put inside dd block is irrelevant.

**Comment by mauritsvanrees** [comment]
This template looks pretty wrong indeed... All the dynamic content should have `i18n:name` in it, so for example `<span i18n:name="language" tal:replace="view/language"></span>`. Same for the `ul` tag.
I guess the i18n stuff from the span `create-object-without-translation` can be removed entirely, although the `a` tag needs an `i18n:name` again.

Or split the translation of the `dd` in two parts:
1. "This object is going..." + the `ul`.
2. The span plus `a` tag.

With a template this broken, I don't think you should worry about trying to preserve existing translations in `po` files.

**Comment by djowett** [comment]
Resolved on 2.x by #216
Still to do on master

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
