### ISSUE TITLE
Rendering not correct

### ISSUE THREAD

**Issue by diti76** [plone/plone.app.multilingual#203]
In some cases the rendering is not correct. The save button is partially (sometimes totally hidden). See picture. By clicking on an available translation button the rendering will then be correct. This suggested to me to force an update_view after document_ready(). 
Maybe this is not the correct solution but it helped me.
I added 
 setTimeout(function () {update_view();}, 1000); in babel_helper.js at line 228 (end of document.ready funtion...)
...
        // Fetch default content
        var initialFetch = $('#trans-selector button.active').data('url');
        // Can be null if not buttons, but the drop-down is present
        if (initialFetch === null) {
            initialFetch = $('#trans-selector select option:selected').val();
        }
        $('#frame-content').load(initialFetch, function () {
            $("#frame-content fieldset legend").unwrap().remove();
            update_view();
        });
        $(".formTabs, .pat-autotoc a").click(sync_elements_vertically);
 ---->        setTimeout(function () {update_view();}, 1000);  <----
    });
}(jQuery));
....

![translation](https://cloud.githubusercontent.com/assets/15149070/11652184/98366d6c-9d96-11e5-8389-725c0a463c4e.png)

**Comment by jensens** [comment]
fixed by merge of plone/plone.app.multilingual#266
