### ISSUE TITLE
Incorrect meta link alternate

### ISSUE THREAD

**Issue by Rudd-O** [plone/plone.app.multilingual#206]
Hi, with p.a.m installed, the <head> of my site contains this:

```
<link rel="alternate" href="http://127.0.1.1:8080/Rudd-O.com/es/ggregator" hreflang="es" /><link rel="alternate" href="http://127.0.1.1:8080/Rudd-O.com/en/egator" hreflang="en" />
```

(that is the raw non-proxy-passed content retrieved from the site in the same server)

Note that the link ought to be /es/aggregator and /en/aggregator.  There is something funky going on in how the alternate references are being processed.

**Comment by Rudd-O** [comment]
I believe my site is using p.a.m 2.0.1.

**Comment by petschki** [comment]
this is a duplicate of #153 isn't it?

**Comment by Rudd-O** [comment]
Yep.  Mark it as a dupe.

**Comment by Gomez** [comment]
Closed as dupe
