### ISSUE TITLE
Media folder should only show up in active language

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.multilingual#207]
The media folder and items within that folder get shown for every configured language, displaying mulitple versions for the same item.

Imho the language independent folder "media" should only show in the active language.

Is there a way to filter LIF folder or should the start node for the widget better be the navigation root?

![screen shot 2016-02-01 at 16 20 57](https://cloud.githubusercontent.com/assets/365761/12721444/1f7d41bc-c900-11e5-9fb9-8890434b85a3.png)

**Comment by jensens** [comment]
classical bug i' say.

**Comment by agitator** [comment]
this also bit mit while using dexterity.membrane users, 
the lookup on login results in non unique users and therefore in an error.

what's the best way to fix this? any pointers?
@datakurre @mauritsvanrees @gforcada @jensens

**Comment by agitator** [comment]
solved the member issue by moving it out of lif folder

**Comment by agitator** [comment]
seems to be not an issue anymore with coredev from today

**Comment by datakurre** [comment]
Ok, so this was probably not so much of an issue in p.a.m. but issue in catalog vocabulary, which showed results beyond navigation root.
