### ISSUE TITLE
sitemap.xml.gz fails

### ISSUE THREAD

**Issue by 2silver** [plone/plone.app.multilingual#209]
If pa.multilingual is installed, generating the "/sitemap.xml.gz" File fails silently, because "LIF", "LRF" are not indexed or searched
Only Plone Root (ex. /Plone) will be shown in the xml

Steps to reproduce:
- working (without pa.multilingual)
  - Install new Plone
  - Go to Website Configlet, activate "sitemap.xml.gz"
  - open, download and view "sitemap.xml.gz"
  - it should be contain ../news, ../events, and Members - the default content
- not working (with pa.multilingual)
  - Install new Plone
  - Install pa.multilingual
  - (Test if LIF and LRF are enabled in "Search"-Configlet)
  - open, download and view "sitemap.xml.gz"
  - It contains only our Plone-Root

Plone Versions:
Plone 4.3.4
pa.multilingual 2.0.1
plone.app.layout 2.3.12

Plone 5.0
pa.multilingual 3.0.12
plone.app.layout 2.5.15

**Comment by djowett** [comment]
+1. However, sitemap.xml (without the gz) *does* give valid results!

Hmmm

**Comment by djowett** [comment]
https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/sitemap/sitemap.py#L57
https://github.com/plone/documentation/issues/537

**Comment by djowett** [comment]
No, sorry, I had fourdigits.seo installed, and I didn't realise that it was providing the working sitemap.xml.
Without it, it's exactly how you say.  

Plone 4.3.8
p.a.multilingual 2.0.2
plone.app.layout 2.3.14

This comment states the issue, but there's no approved resolution
https://github.com/plone/plone.app.layout/pull/8#commitcomment-6551154

**Comment by djowett** [comment]
[This](https://github.com/plone/Products.LinguaPlone/blob/90061910b19802b1f31a50f1a809b6a90016c81b/Products/LinguaPlone/patches.py#L22) is the relevant patch in Linguaplone

**Comment by djowett** [comment]
This is resolved by the following PRs (note that the main fix is in `plone.app.layout`):

* #236 for PAM 1.x on Plone 4.3 (1.x was already working, but this keeps it so)
* #234 for PAM 2.x on Plone 4.3
* #255  for PAM master (now 5.x branch) for Plone 5.0 or 5.1

These versions should work:
Plone 4.3.x
pa.multilingual ~2.0.3 (version TBC when released)
plone.app.layout 2.3.16

Plone 5.0
pa.multilingual 5.0.1
plone.app.layout 2.5.22

Plone 5.1
pa.multilingual 5.0.1
plone.app.layout 2.6.3

**Comment by jensens** [comment]
@djowett good work, thanks you very much!

**Comment by djowett** [comment]
Glad that's out the way! Thanks @jensens, @erral and @mauritsvanrees for the back up in merges, feedback and releases :-)

**Comment by mauritsvanrees** [comment]
I have released plone.app.multilingual 1.2.3, 2.0.3, and 5.0.2
