### ISSUE TITLE
formcontrols not accessible in babelview - overlapped by TinyMCE?

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.multilingual#217]
did someone come across this issue?
Plone 5.0.3rc1with p.a.multilingual from master (same problem on Plone 5.0.2 with pam 3.0.15)
something wrong with TinyMCE?

![screen shot 2016-03-07 at 15 08 34](https://cloud.githubusercontent.com/assets/365761/13585156/6c18cca0-e4ba-11e5-9209-aef1a8aba055.png)

 @vangheem @datakurre @saily ?

**Comment by agitator** [comment]
maybe connected to https://github.com/plone/plone.app.multilingual/issues/203 ?

**Comment by agitator** [comment]
it seems that if you already have more than one translation of your content as in the screenshot above, switching between the two existing version via the buttons somehow fixes/sets the height for the forms.
is there a js that is being called too late or not at all?

**Comment by saily** [comment]
check babel view is missing a clear `div` after those columns. i don't think this is related to tinymce pattern issue.

**Comment by agitator** [comment]
checked again it's babel_helper.js that sets the height of the fieldset.
somehow update_view or similar isn't called on $(document).ready, but don't see in what context it has to be called to work.
@do3cc i saw you had you're fingers in there, do you know how to fix that?

**Comment by do3cc** [comment]
You mean my changes from 2012? 4f03ff811cb83af72ea95a4a22e1fc459efafd22
Sorry, no idea.

**Comment by jensens** [comment]
fixed by merge of plone/plone.app.multilingual#266
