### ISSUE TITLE
Original translation isn't loaded

### ISSUE THREAD

**Issue by kcleong** [plone/plone.app.multilingual#220]
When adding a translation in Plone toolbar using Translations -> Create [language], the original language (left column in `++addtranslation++` view) won't load because of CSRF protection. Sometimes the iframe in left column is loaded but more often the column shows a CSRF warning page  (see screenshot below). When I click the 'confirm action' I get redirected to a bare page showing the babel_view of the original content.

![screen shot 2016-03-09 at 09 44 02](https://cloud.githubusercontent.com/assets/201650/13629792/b1cade24-e5db-11e5-8981-50d947068727.png)

I solved it by overriding the `plone.app.multilingual.browser.templates.dexterity_edit.pt` template using z3c.jbot. In the template I added the csrf token to the `babel_view`. I can provided a branch with the fix in p.a.multilingual if needed. See `csrf_token` in https://gist.github.com/kcleong/cbf25ad2cd42e6f5bc0a the overriden template.

**Comment by kcleong** [comment]
I am using Plone 5.0.2 and this is happening on default dexterity content and on custom dexterity content types.

**Comment by agitator** [comment]
have you tried with the latest version of p.a.multilingual?
