### ISSUE TITLE
plone.app.multilingual breaks selected tab highlight on Plone 5

### ISSUE THREAD

**Issue by siebo** [plone/plone.app.multilingual#222]
I have a vanilla Plone 5 site and installed plone.app.multilingual with Dutch and English language tracts, with Dutch as the default language.  Now the 6th tab has the selected class and visual highlight no matter which section a user is in.
I see the same bug in a blank site after installing only plone.app.multilingual and creating a few test pages.

**Comment by erral** [comment]
This was a bug in plone.app.layout when creating the navbar:

https://github.com/plone/Products.CMFPlone/issues/1178

But it was already fixed and released in plone.app.layout 2.5.16 and Plone
5.0.2

https://github.com/plone/plone.app.layout/pull/69



On Wed, Mar 9, 2016 at 10:56 PM, David Siedband <notifications@github.com>
wrote:

> I have a vanilla Plone 5 site and installed plone.app.multilingual with
> Dutch and English language tracts, with Dutch as the default language. Now
> the 6th tab has the selected class and visual highlight no matter which
> section a user is in.
> I see the same bug in a blank site after installing only
> plone.app.multilingual and creating a few test pages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/plone.app.multilingual/issues/222>.
>



-- 
Mikel Larreategi
mlarreategi@codesyntax.com

CodeSyntax
Azitaingo Industrialdea 3 K
E-20600 Eibar
Tel: (+34) 943 82 17 80
