### ISSUE TITLE
I failed to install "plone.app.multilingual" in Plone 4.3.8. 

### ISSUE THREAD

**Issue by Gonchin** [plone/plone.app.multilingual#223]
Hi 
It seems that "plone.app.multilingual" no longer supports Plone 4.3.x.  
I failed to install "plone.app.multilingual" in Plone 4.3.x. as follows.  
----------
For using this package with Dexterity content types I added my *eggs* buildout section::

    eggs =
        plone.app.multilingual [dexterity]

-----------

The both of Plone 4.3.7 and 4.3.8 do not work.  

I have no idea.  Help me.
Thank you.

**Comment by petschki** [comment]
do you have pinned to the right version? https://github.com/plone/plone.app.multilingual#versions

**Comment by Gonchin** [comment]
Yes, I tried the version 1.x or 2.x of this addon.  
Do you know the sutable version no. for Plone 4.3.8?
Thank you for your comment.

**Comment by petschki** [comment]
well ... suitable version is described in README. maybe you can provide a traceback for more investigation

**Comment by Gonchin** [comment]
OK.
I will show the detail information.  For example, "buildout.cfg" and error messages etc.  
Thank you.

**Comment by Gonchin** [comment]
I edited the buildout.cfg as follows.

**Case 1. no pinned version**
[buildout]
egg = 
     plone.app.multilingual [dexterity]
[versions]

After buildout, the console message shows as follows.
_UnknownExtra: plone.app.multilingual 2.0.0 has no such extra feature 'dexterity'_

**Case 2. version 1.0**
[buildout]
egg = 
     plone.app.multilingual [dexterity]
[versions]
     plone.app.multilingual = 1.0

After "buildout", the console message shows as follows. 

  Versions had to be automatically picked.
  The following part definition lists the versions picked:
  [versions]
  plone.multilingual = 1.2.1
  plone.multilingualbehavior = 1.2.1
  plone.recipe.command = 1.1
  plone.recipe.precompiler = 0.6
  
  # Required by:
  # plone.app.multilingual==1.0
  archetypes.multilingual = 3.0.2

Then restart
Plone: _503 service Unavailable_

**Case 3. version 2.0**
[buildout]
egg = 
     plone.app.multilingual [dexterity]
[versions]
     plone.app.multilingual = 2.0

After buildout, the console message shows as follows.
_UnknownExtra: plone.app.multilingual 2.0.0 has no such extra feature 'dexterity'_


It seems that "plone.app.multilingual 2.0" has been removed. 
I have no idea.

**Comment by djowett** [comment]
If you are (as it seems) starting from scratch, and you want to use dexterity, then you should add plone.app.contenttypes (1.1 branch) to your eggs, and use plone.app.multilingual 2.x branch ([you can see the available recent releases on pypi](https://pypi.python.org/pypi/plone.app.multilingual) - 2.0 does not exist, so you should probably choose 2.0.2 ).  You can remove the "dexterity" feature in 2.x branch.

So:

     [buildout]
     ...
     eggs =
          plone.app.contenttypes
          plone.app.multilingual
    ...
    [versions]
    ....
    plone.app.contenttypes = 1.1
    plone.app.multilingual = 2.0.2

**Comment by Gonchin** [comment]
Hi, Mr. djowett,
The installation is successful.  Thank you for your magic bullet. 
However, I cannot choose Chinese character set.  
Anything else?

**Comment by djowett** [comment]
Go to the languages control panel

<your-site>/@@language-controlpanel

On 22/03/16 14:55, Gonchin wrote:
>
> Hi, Mr. djowett,
> The installation is successful. Thank you for your magic bullet.
> However, I cannot choose Chinese character set.
>
> Anything else?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/plone/plone.app.multilingual/issues/223#issuecomment-199852012>
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by djowett** [comment]
assuming this is sorted

**Comment by Gonchin** [comment]
Thank you for your advice.  
Chinese character set becomes Japanese.  It seems that Chinese character set is not ready for Plone 4.3.

**Comment by djowett** [comment]
That might be a general Plone issue rather than a problem with 
plone.app.multilingual.   But it's more likely "just" to be a missing 
translation.  New translations are always welcome.

I presume you have correct character sets loaded on your PC?

A screenshot of the issue might help.

On 22/03/16 20:11, Gonchin wrote:
>
> Thank you for your advice.
>
> Chinese character set becomes Japanese. It seems that Chinese 
> character set is not ready for Plone 4.3.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> <https://github.com/plone/plone.app.multilingual/issues/223#issuecomment-199999300>
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by Gonchin** [comment]
I close this issue.
Then I will issue a new one as to Chinese character-set in Plone 4.3. Thank you.
