### ISSUE TITLE
Display menu is not translated

### ISSUE THREAD

**Issue by djowett** [plone/plone.app.multilingual#224]
Menu items under the display menu are not translated for the Language Root Folder

![display_menu_not_translated](https://cloud.githubusercontent.com/assets/1470021/13960283/97d437c6-f04f-11e5-8413-0e7fe920a866.png)

After a bit of searching around it was obvious - the old view names are still being used!

```
  <property name="default_view">folder_listing</property>
  <property name="view_methods">
    <element value="folder_summary_view"/>
    <element value="folder_full_view"/>
    <element value="folder_tabular_view"/>
    <element value="atct_album_view"/>
    <element value="folder_listing"/>
  </property>
```

Fixes required for 2.x & 3.x.  Not 1.x as that is not using plone.app.contenttypes

**Comment by djowett** [comment]
The following `profiles/default/types/LRF.xml` will work in another product, but I don't seem to be able to get it working by changing the corresponding file in PAM itself. A bit peculiar...

    <?xml version="1.0"?>
    <object name="LRF" meta_type="Dexterity FTI" i18n:domain="plone"
       xmlns:i18n="http://xml.zope.org/namespaces/i18n">

     <property name="default_view">listing_view</property>
     <property name="view_methods">
      <element value="summary_view"/>
      <element value="full_view"/>
      <element value="tabular_view"/>
      <element value="album_view"/>
      <element value="listing_view"/>
     </property>

    </object>

**Comment by djowett** [comment]
Any takers to help on this, I guess it's easy if you know how!...

**Comment by marcyang001** [comment]
Is this happening on Plone 5 or 4?

**Comment by marcyang001** [comment]
I will take a look at it. I will take a look at Plone 3 as oppose to 5 now

**Comment by djowett** [comment]
It's on plone 4.3 for me.  But I can see the issue in LRF.xml  for the 
master branch too.

Thanks for the help!

On 23/03/16 18:10, Marc Yang wrote:
>
> Is this happening on Plone 5 or 4?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/plone/plone.app.multilingual/issues/224#issuecomment-200471875>
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com
