### ISSUE TITLE
Plone 4.3.8 is missing Chinese character-sets for the multilingual use.

### ISSUE THREAD

**Issue by Gonchin** [plone/plone.app.multilingual#225]
I guess that Plone 4.3.8 has no Chinese character-sets for multilingual use.  
Chinese selected on @@language-control panel becomes to Japanese.  
Please see the figures as follows.

![plone 4 zh](https://cloud.githubusercontent.com/assets/7365507/13982828/87eac362-f12f-11e5-910d-6cbeee8b5402.jpg)
**Fig. 1 Chinese site of Plone 4.3.8: "ホーム" (= Home) is Japanese. -- Wrong **

![plone 5 zh-cn](https://cloud.githubusercontent.com/assets/7365507/13982834/8e122fa0-f12f-11e5-9870-c7a39bf4d672.jpg)
**Fig. 2 Chinese site of Plone 5.0.2: ”首页” (= Home) is Simplified Chinese. -- Normal **

**Comment by djowett** [comment]
@Gonchin please try with Plone 5.0.3 or 5.0.4 as locales have been updated in those products.  Nonetheless it should still be working as the string you mention IS in plone.app.locales [here](https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/locales/zh_CN/LC_MESSAGES/plone.po#L2570).

The translation of Home is nothing to do with plone.app.multilingual, so please report any issue under [Products.CMFPlone](https://github.com/plone/Products.CMFPlone) - link back here if you like, but I'm closing this issue.

**Comment by Gonchin** [comment]
Thank you for your comment.  
You mean that Plone 4.3.x does not support Chinese?
Plone 4.2.x with LingualPlone supports Chinese and Taiwanese. 
You know that Plone 5.0.3 and 5.0.4 do not work the "full-text search" well at present.
We need these functions (multilingual and full-text search).  
Should I report the section of Product.CMFPlone?

**Comment by djowett** [comment]
@Gonchin No I didn't mean that - I got confused over which version of Plone you had an issue with.

**Comment by djowett** [comment]
I don't do/speak Chinese, so can you confirm this is correct? looks so to me.

![sitemap screenshot zh-cn](https://cloud.githubusercontent.com/assets/1470021/15075800/22848206-139e-11e6-9d9d-cfd5c296545e.png)

URL is
http://localhost:8087/mysite/zh-cn/sitemap?set_language=zh-cn

Buildout config includes:

    proj-environment-vars =
        zope_i18n_compile_mo_files true
        TZ Europe/London
        PTS_LANGUAGES en de pt pl zh zh-cn zh_CN
        zope_i18n_allowed_languages en de pt pl zh zh-cn zh_CN

I found that zh-cn & zh make no difference, only *zh_CN* loads the translations.

@l34marr any comments? (sorry to hassle you again)

**Comment by l34marr** [comment]
If appropriate, I'd like to see zh (Chinese) to use zh-tw (Traditional Chinese) translations by default for plone.app.multilingual. I am the zh-tw translation contributor and keep it almost fully translated. Hopefully this will solve this kind of issues by and large.

For those who are not native Chinese speakers, they might regard Traditional Chinese no different than Simplified Chinese, just like how non-native-English-speakers see "optimize" vs "optimise".

Ref: https://community.plone.org/t/i-set-personal-preferrence-language-to-my-preferred-lanaguage-but-the-gui-still-shows-english/1411/9

**Comment by djowett** [comment]
@l34marr thanks loads for your input on these two questions.

I'm still finding my way in multilingual sites, but it seems to me there's an issue to be logged against CMFPlone here over the ordering of Chinese translations and which to use by default.  Would you agree?

But I'm not sure I can quite express it precisely enough, so would be grateful if you raised the issue if so! (You'll get my +1)

**Comment by l34marr** [comment]
@djowett I would like to help and look into this issue by mid-June, when our local event PyCon Taiwan ends.
