### ISSUE TITLE
migration of ATCT content to plone.app.contenttypes and Language='all'

### ISSUE THREAD

**Issue by martior** [plone/plone.app.multilingual#226]
When running the migrations in plone.app.contenttypes on Plone 5 with plone.app.multilingual  installed it doesn't find any content to migrate. This is because it adds Language='all' to the query if it detects LinguaPlone or plone.app.multilingual. Then if you run the migrations directly from script the walker from Products.contentmigration also adds the same query.

I migrated from LinguaPlone to plone.app.multilingual on a Plone4.3 version of the site and uninstalled Linguaplone there.

So my question is, should Language='all' catalog queries work with plone.app.multilingual and there is something wrong with my site? Testing on a new Plone5 site and looking at plone.app.contenttypes code indicates that Language='all' no longer works. This probably means we need to update the migration code. As far as I can see the check HAS_LINGUA_PLONE and HAS_MULTILINGUAL is only used to add Language='all' to the search criteria. 

plone.app.contenttypes.migration.utils.HAS_MULTILINGUAL
Products.contentmigration.common.HAS_LINGUA_PLONE

**Comment by bsuttor** [comment]
Hello,

I have the same issue. There is nothing wrong in your site.

I think it's a plone.app.multilingual bug, catalog requests are always set for all languages, we should think about added a 'search_catalog' method which set context language or preferred language during catalog request (and set all language when you choose all).

Products.LingualPlone implemented that :

https://github.com/plone/Products.LinguaPlone/blob/master/Products/LinguaPlone/catalog.py
https://github.com/plone/Products.LinguaPlone/blob/master/Products/LinguaPlone/patches.py

**Comment by martior** [comment]
Yeah, it might be something that was removed from p.a.multilingua though. As far as I understand, p.a.m uses nav root to separate languages, so the catalog monkey patching are not needed any more. So I think the correct solution is to make the checks:
plone.app.contenttypes.migration.utils.HAS_MULTILINGUAL
Products.contentmigration.common.HAS_LINGUA_PLONE
only check for Linguaplone. 

Some history as far as I understand it in case anyone is interested: Early linguaplone didn't have language folders and used the catalog patches to hide content not of the current language by adding a Language={current_language} to all catalog queries, this worked because the navigation was also controlled by the catalog. The Language='all' was the only way to get all content. With language folders that also are navigation roots the adding of the Language query is no longer needed, and with the move from Linguaplone to p.a.m. this seem to be removed. The migration code needs to catch up.

**Comment by djowett** [comment]
Just seen this issue after working on #209, #234 and "friends".

I don't think they overlap, but just to say, please lets leave Language='all' behind with LinguaPlone & not bring it further in to Plone 5 technology!  Though it is in 1.x branch of Plone App Multilingual

cc @erral
