### ISSUE TITLE
TinyMCE window overlaps with Save in split-view

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.multilingual#227]
TinyMCE window overlaps with buttons. Workaround: Click on tab before.
![screenshot from 2016-04-06 11 49 13](https://cloud.githubusercontent.com/assets/157140/14312749/f4ad9574-fbed-11e5-9db0-0b4df38239d2.png)

**Comment by jensens** [comment]
Todo: fix and remove line added in 6c9c0cc18f3c87f7020450cc50ae859978a4df1

**Comment by agitator** [comment]
most probably connected with https://github.com/plone/plone.app.multilingual/issues/217

**Comment by jensens** [comment]
@agitator was this fixed by merge of plone/plone.app.multilingual#266 ?

**Comment by agitator** [comment]
Didn't happen to me after the change, problem was that tinymce wasn't fully loaded and so didn't return the correct height. I'd say reopen if it happens again...
