### ISSUE TITLE
Using plone.app.multilingual, is it possible to keep content revisions?

### ISSUE THREAD

**Issue by simonbc** [plone/plone.app.multilingual#228]
I am currently running Plone 4.2 using Archetypes/LinguaPlone and trying to determine whether migrating to Plone 5.0 with Dexterity/plone.app.multilingual might solve the issues I have with my current setup.

Right now my Archetypes/LinguaPlone setup forces me to turn off content revisions and so I'm curious to know, if migrating to Dexterity/plone.app.multilingual might solve this issue. 

In other words, is it possible with Dexterity/plone.app.multilingual to keep revisions of content across multiple languages?

Thanks!

**Comment by datakurre** [comment]
I'm sorry for this being left unanswered. It's hard to believe that LinguaPlone prevents that.

Anyway, with p.a.m each translation has its own version history, so it should be possible.
