### ISSUE TITLE
Deleting an Language Resource Folder wipes my Media folder

### ISSUE THREAD

**Issue by djowett** [plone/plone.app.multilingual#232]
... yes, for all languages

This can be reverted through the Undo tab in the ZMI, but still  not nice :-(

**Comment by datakurre** [comment]
@djowett I recall it really unindexes all the other languages, but those could be restored into catalog with clear and rebuild. But I agree that it is not nice. Need to investigate could detect that its LIF that's being removed and prevent undexing the other languages.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.

**Comment by djowett** [comment]
Thanks for update - no worries from me.... it was an old version and I'm not using PAM now.
