### ISSUE TITLE
RelatedItems widget not working as expeced after installing PAM

### ISSUE THREAD

**Issue by krissik** [plone/plone.app.multilingual#238]
I have a site with plone.app.multilingual installed and I`d like to use the RelatedItems widget. If I just start typing into the Search Section (keul called it so - https://community.plone.org/t/about-the-new-plone-5-related-items-widget/1462) everything works as expected. But if I try to narrow the search by using the Explore Section no item is show anymore.

If you would like to reproduce it:
- create a site
- install plone.app.multilingual
- configure 2 languages
- create a page in a language root folder (e.g. start)
- create a folder in this language root folder (e.g. folder1)
- create another page in this subfolder (e.g. folder1/page1)
- edit the first page (start) - go to categorization tab
- type `page1` to relateditems widget => page1 item is displayed
- click top left icon of the relateditem widget  to select a folder
- select folder1 in your language folder
- it says "no matches" found => but I would expect to see page1 here

I have found out, that in the second case the catalog is called with a wrong path parameter in plone.app.vocabularies - catalog.py:

```
{u'path': {'query': [u'/testrelateditemswidget/en/en'], 'depth': 1}, 'sort_on': u'sortable_title', 'sort_order': 'ascending'}
```

There is two times `en` in the path.

tested versions:

plone.app.multilingual 3.0.16 and 4.0.2
plone.app.vocabularies 2.2.3 and 3.0
plone.app.querystring 1.3.14 and 1.3.15
plone.app.content 3.1.1

I hope someone can help.

**Comment by jensens** [comment]
iirc we had the same problem. @thet and I did a bunch of fixes already. You may want to try buildout.coredev on the 5.1 branch to check if this is true for your case too.

**Comment by andreesg** [comment]
The same issue is happening here with Plone 5.0.6

Tested versions:
plone.app.multilingual 3.0.16
plone.app.vocabularies 2.2.3
plone.app.querystring 1.3.14
plone.app.content 3.1.1

Thanks for the suggestion @jensens, it's great that so many fixes have been released.
Unfortunately upgrading the Plone version to the 5.1 branch didn't solve the problem.
Is there any other product that needs to be updated using a Github branch that I'm overlooking? 

Any ideas? @jensens @thet

**Comment by krissik** [comment]
I have tested the RelatedItemsWidget with coredev 5.1 (minimalplone5 - cordev.cfg). There I can not select an item from an other language root, e.g. if I am at 'de' I can not select an object from 'en'. Is that intended?

I have figured out that the problem seems to be at plone.app.querystring https://github.com/plone/plone.app.querystring/blob/master/plone/app/querystring/queryparser.py#L290

If a Language Root Folder (e.g. 'de') is selected in the widget the value for `root` is `/Plone/de` and for `values` `de`. After concatenate both strings we have `/Plone/de/de`, which is wrong. I would work around this problem but I am not sure if this is a good idea.

```python
    if not values.startswith(root):
        # if root is LRF (e.g. /Plone/de) and values is LRF too (e.g. /de)
        # do not concatenate to avoid doubling of language root folder id (e.g. /Plone/de/de)
        if (context.restrictedTraverse(root).portal_type == u'LRF'
           and values.split('/')[1] == root.split('/')[-1]):
            values = root + '/'.join(values.split('/')[2:])
        else:
            values = root + values
```

**Comment by datakurre** [comment]
I've also seen this. The current related items widget behavior (latest versions ) is to restrict selecting anything above the closest navigation root, and language root folder is a navigation root. And that seems to be pretty hard to go around. I needed to override pattern configuration (fix widget basePath) and add multiple monkeypatches to let RelatedItemsWidget see above navigation root (fix widget basePath elsewhere, patch queryparser and patch related vocabulary).
