### ISSUE TITLE
pa.multilingual 2.0a3 -> 2.0.1 breaks portal_catalog

### ISSUE THREAD

**Issue by 2silver** [plone/plone.app.multilingual#241]
Steps to reproduce:
- Install Plone
  - make Catalog rebuild -> works
- buildout with pa.multilingual = 2.0a3 
  - install pa.contenttypes (needed)
  - install pa.multilingual
  - create languages (de/en)
  - make per language a testsite (seperate, not linked, error depends on)
  - make Catalog rebuild -> works
- buildout with pa.multilingual = 2.0.1
  - make Catalog rebuild -> failed
  - not needed to reinstall pa.multilingual

```
    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module Products.CMFPlone.CatalogTool, line 446, in manage_catalogRebuild
      Module plone.app.discussion.patches, line 47, in patchedClearFindAndRebuild
      Module OFS.FindSupport, line 239, in ZopeFindAndApply
      Module OFS.FindSupport, line 198, in ZopeFindAndApply
      Module Products.ZCatalog.Lazy, line 190, in __getitem__
      Module plone.folder.ordered, line 94, in <lambda>
      Module plone.folder.ordered, line 59, in _getOb
    AttributeError: 'portal_setup'
```

Plone 4.3.4
Plone 4.3.9
plone.app.multilingual 2.0a3 (2.0.1)

And, the  Language Folders arent undeleteable after 2.0.1

**Comment by jensens** [comment]
The old language root folder implementation left garbage ids in the IOrdering of the folder. This need a manual cleanup. An example here https://gist.github.com/jensens/356ab35614c4c0a7c626d8ba4a7a8479 - you may need to append values to the blacklist, depending on language and addons installed.

**Comment by jensens** [comment]
The above view/script need to be run on every LRF.

I do not think we need to fix this, since it comes from an alpha version. There are probably only very few people around using this version. Opinions?

**Comment by jensens** [comment]
ok to close
