### ISSUE TITLE
ImageBrowser and LinkBrowser don't show correct content for Static Portlet

### ISSUE THREAD

**Issue by djowett** [plone/plone.app.multilingual#244]
For english (the default language in my case) they show the correct content - within the EN LRF, but for other languages they show the contents of SiteRoot - which is not correct & doesn't enable me to add a link / image from anywhere (even the Media folder).

In my case SiteRoot only has 4 LRF folders and the Members folder, and the following is what I see:

![imagebrowser screenshot](https://cloud.githubusercontent.com/assets/1470021/17373775/a9215476-59a1-11e6-9c65-2bdfa4b41aae.png)

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
