### ISSUE TITLE
Uploading an image in TinyMCE fails with p.a.multiligual

### ISSUE THREAD

**Issue by pbauer** [plone/plone.app.multilingual#252]
When p.a.m. is installed uploading a image fails since the url used for the POST-request is wrong.

Example using demo.plone.de:
When trying to upload a image from within TinyMCE to http://demo.plone.de/en/demo/a-page the url that is used for the POST is http://demo.plone.de/demo/@@fileUpload instead of http://demo.plone.de/en/demo/@@fileUpload.

**Comment by cekk** [comment]
i think that this is solved in 5.1a2 version on Products.CMFPlone with this issue: https://github.com/plone/Products.CMFPlone/issues/1513

**Comment by erral** [comment]
Pull request for this in Plone 5.0.x: https://github.com/plone/Products.CMFPlone/pull/1919

**Comment by erral** [comment]
The pull request is included already in both Plone 5.0.x and 5.1, so we can close this.
