### ISSUE TITLE
Feature Request : Redirect to a missing translation page instead of redirecting to the parent folder

### ISSUE THREAD

**Issue by RomainCo** [plone/plone.app.multilingual#254]
The need is to redirect clients to an explicit missing translation entry when the related translation doesn't exist.

A (maybe quick & dirty) solution is to modify helper_views.py :

Comment "return self.wrapDestination(translation.absolute_url(),postpath=False)" at the end of the getClosestDestination() function, and add just before : 

return site.absolute_url()+"/"+ltool.getPreferredLanguage(self.request)+"/missing-translation"

To use it, you have to create a "missing-translation" page in each of your site languages, inside the root language folder.

**Comment by erral** [comment]
This is already an option in p.a.multilingual.

You need to go http://yoursite.com/@@language-controlpanel clic on the "Multilingual" tab and change the translation lookup policy (last dropdown option).
