### ISSUE TITLE
Travis is not checking test results on master branch

### ISSUE THREAD

**Issue by djowett** [plone/plone.app.multilingual#256]
We only run one combination: Python 2.7 & Plone 5.0.  And it is permitted to fail.
Hmm

    python:
    - 2.7
    ....
    env:
      matrix:
      - PLONE_VERSION=5.0
    ...
    matrix:
      allow_failures:
      - python: 2.7
        env: PLONE_VERSION=5.0

**Comment by gforcada** [comment]
@djowett does it make any sense to keep travis as pam is already part of Plone core and thus is tested in jenkins.plone.org? /me wonders

**Comment by djowett** [comment]
@gforcada possibly not
However, fix for this issue coming in 6d57ac9, and fix for tests in cef86100

**Comment by djowett** [comment]
Resolved by 58c7556bd2b54a9612193af7c4e9a26d1a184bb7. Tests fixed in 389aebc2800df64648cd37545cc271e799a2f839
