### ISSUE TITLE
Update 2.0.1 > 2.0.3 breaks Language Relations

### ISSUE THREAD

**Issue by 2silver** [plone/plone.app.multilingual#258]
buildout from [buildout.coredev](https://github.com/plone/buildout.coredev/tree/4.3)

Steps to reproduce:
 - make clean buildout
 - add pa.contenttypes
 - add pa.multilingual = 2.0.1
 - install second language (en/de)
 - add some Folders/Documents
 - link content to other langauge
 - switching between languages works fine
 - update pam -> 2.0.3
 - run buildout again
 - reinstall pam (quickinstaller)
- Translations lost (@@multilingual-map - Missing translations)

Plone 4.3.12.dev0
plone.app.contenttypes 1.1.1
plone.app.multilingual 2.0.1 > 2.0.3

**Comment by agitator** [comment]
why did you reinstall pam?
As I recall quickinstaller does all (maybe wrong) sorts of things, not sure about that though.
I'd only check if there is an upgrade step available in portal_setup and do that.

**Comment by jensens** [comment]
portal_setup re-apply profile works fine, quickinstaller (deprecated anyway) destroys the settings.

**Comment by jensens** [comment]
communicated with @2silver  - we can close this one.
