### ISSUE TITLE
Translate menu is not shown in Navigation root items

### ISSUE THREAD

**Issue by erral** [plone/plone.app.multilingual#262]
Objects that provide INavigationRoot interface do not show the translate menu:

https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/browser/menu.py#L64

I think this was intended not to show the translate menu on the top-most language root folders. 

Now, we have a dedicated content object for that with a dedicated interface [ILanguageRootFolder](https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/interfaces.py#L21), so I think that the translation menu check should be done for this interface instead of for INavigationRoot.

@libargutxi

**Comment by jensens** [comment]
closed by merging #263
