### ISSUE TITLE
No Option to Set Google Translate API Key

### ISSUE THREAD

**Issue by glimmung** [plone/plone.app.multilingual#275]
In p.a.m 5.0.3, under Plone 5.0.7, there is no option to set this key.

In the 2.0.x series, this was on the "Extra Options" tab.

I've searched the issues here, and had a look at the changelog, but I don't see any clue.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
