### ISSUE TITLE
copy/paste/move should not be allowed between lrf-branches

### ISSUE THREAD

**Issue by iham** [plone/plone.app.multilingual#276]
when adding a new page, it is - according its language root folder - for example english.
using actions and cut that object.
now go to a different language (eg. german)
and now hit actions - paste.

the object will be in the pasted and gets the language of its lrf it has now.

question: WHY?
doing that breaks the "translate into" use case and leaves an english intended object as german.

why is it done that way?

i would prefer a protection to avoid doing that and make it configure able which strategy should be used (avoid paste/move or reset language)

**Comment by agitator** [comment]
So I tried to reproduce
- created a site in de and en
- created a page in de
  - lang property on object is de
- cut and pasted it to en
  - lang property on object is en
  - I can translate it do de again

imho this is the functionality as expected

Do you want to prevent that users copy/cut content over to another language?
Such a feature could be useful in some cases...
But I'd say it should be configurable from the control panel and off by default.

**Comment by agitator** [comment]
please reopen if not answered, pull request welcome if you want that feature ;-)
