### ISSUE TITLE
single language does not create a lrf

### ISSUE THREAD

**Issue by iham** [plone/plone.app.multilingual#300]
as the title tells: why is that not happening?

i wanted to create a single language to be prepared for further upcoming languages which might be added later AND to have a root folder to restrict addable contenttypes.

when setting two languages are set, the pam creates those two folders are created. when i then remove one language the corresponding folder is deleted and the second lrf is not. so having only one lrf is basically possible, but a bit hacky to do it that way.

allowing a single language also to create a lrf would be good.

**Comment by iham** [comment]
... ok i found out the setupSite method CAN handle a **forceOneLanguage**

it would "only" need a checkbox in the control panel and a modification on the save-handler of that form.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
