### ISSUE TITLE
Missing Google Translate Icon in PAM 5.1.4 on Plone 5.0.8

### ISSUE THREAD

**Issue by holdenhao** [plone/plone.app.multilingual#302]
After adding my API key, the Google translate icon does not appear.  The browser inspector shows that it is trying to request for the icon from the address:

http://localhost:8080/Plone/++plone++production/++unique++2018-02-20T20:20:59.476385/++resource++plone.app.multilingual.stylesheet/++resource++plone.app.multilingual.images/gtranslate.png

The correct path is: http://localhost:8080/Plone/++resource++plone.app.multilingual.stylesheet/++resource++plone.app.multilingual.images/gtranslate.png

If I se the the resource registry in debug mode, the icon gets the correct address and it appears, however, clicking on it does nothing.  It is supposed to translate the field.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
