### ISSUE TITLE
Google translate gets wrong context

### ISSUE THREAD

**Issue by holdenhao** [plone/plone.app.multilingual#303]
On Babel edit view in PAM 5.1.4 (also in 5.0.7) after a create LANG link is clicked, Google translate gets the parent context instead of the item's context. Google translate then returns the parent's corresponding field translation.

BTW, I am testing this in Plone 5.0.8

**Comment by holdenhao** [comment]
We created a work around in https://github.com/afterfivetech/plone.app.multilingual/commit/6b245ab9eb2387d0856d1ef77f33222f164e3be3

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.

**Comment by erral** [comment]
I can confirm this issue in Plone 6.0.13.

A PR is coming to fix it.
