### ISSUE TITLE
Indonesian root language folder does not have language set

### ISSUE THREAD

**Issue by holdenhao** [plone/plone.app.multilingual#304]
In PAM 5.1.4, the root language folder for Indonesian does not have its language set to "id" at the time of its creation after configuring the language settings in the control panel.  This will result to a permission error when you try to create an Indonesian translation of an item.  The work around is to manually set the language of the folder.

**Comment by jensens** [comment]
This could be still the case, since `id` is reserved internally and maybe not allowed as an identifier.

**Comment by mauritsvanrees** [comment]
For Plone 6.0 I have a fix ready in PR #424.  I want to port it to 5.2 as well.

**Comment by mauritsvanrees** [comment]
Reopening this for one final problem.
If Indonesian is the default language, and you visit the site root for the first time, you are now correctly redirected to the `id-id` folder.  The `I18N_LANGUAGE` cookie also gets set to `id-id`, but this should be `id`.  Probably not a big deal, but let's set it correctly.
I am making PRs.
