### ISSUE TITLE
Transactions on view should not happen

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.multilingual#320]
In several Plone 5.1 site with p.a.multilingual I see transactions on view access - imho that shouldn't happen ...

```
/Plone/fr/medias/consultations/16035769.png/index_html by None
/Plone/de/medien/news/news-xxx/document_view by Plone userxy
/Plone/de/medien/news/Document by Plone userxy
/Plone/de/services/blog/article-xy/edit by Plone userxy
/Plone/de/services/blog/article-xy/edit by Plone userxy
/Plone/it/contatti/contatti/document_view by None
/Plone/de/kontakt/kontakt/document_view by None
/Plone/fr/contact/contact/document_view by None 
```

Has anyone else seen this behavior?

**Comment by agitator** [comment]
@tomgross have you notice something like this on your sites?

**Comment by erral** [comment]
@agitator that's the list shown on Undo tab on ZMI right? I have this right know in a Plone 5.1.2.

**Comment by tomgross** [comment]
@agitator not that I'm aware of. A quick grep for `transaction` in p.a.m shows it occurs only in tests.

**Comment by agitator** [comment]
@erral @tomgross i have an entries for view on almost every object within the undo tag in the zmi

**Comment by erral** [comment]
I have seen the same behaviour on http://demo.plone.de

**Comment by erral** [comment]
Can this be related to this one https://github.com/plone/plone.app.multilingual/issues/315 ?

**Comment by jensens** [comment]
I think the problem of is here:
https://github.com/plone/plone.app.multilingual/blob/dd46093c6b595b2d53b821e7344e57014c4c3ab8/src/plone/app/multilingual/manager.py#L44-L47 
and here
https://github.com/plone/plone.app.multilingual/blob/dd46093c6b595b2d53b821e7344e57014c4c3ab8/src/plone/app/multilingual/manager.py#L59-L62

If no translationgroup attribute was set, the attribute is created. 
Solution is to always actively set an TG after create.

**Comment by agitator** [comment]
Real life impact of this bug...
- Upgraded a client site to Py3 which included packing the zodb to 0 days
- Ran for one week
- ZODB grew to 10.3gb with 1827707 objects
- ZODB after fresh pack 377.7mb with 417011 objects

**Comment by agitator** [comment]
after debugging at ploneconf sprint ferrara, it doesn't seem related to multilingual.
plone.namedfile is more suspicous

**Comment by agitator** [comment]
I also put pdbs in the mentioned lines but they weren't called and transactions still happended
