### ISSUE TITLE
Are your folders ITranslatable? Error

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.multilingual#326]
Plone 5.1.4.

Situation: we are migrating a Plone site over plone.restapi and create folders `en` and  `de` by default
(bare Plone, only one custom package with a Dexterity type `Richfolder`).

At some point I decided to "display flags" and "show language selection" inside the languages control panel. 

I am unable to save the settings due to this error:

``` 
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module plone.z3cform.layout, line 63, in __call__
Module plone.z3cform.layout, line 47, in update
Module plone.z3cform.fieldsets.extensible, line 65, in update
Module plone.z3cform.patch, line 30, in GroupForm_update
Module z3c.form.group, line 145, in update
Module plone.app.z3cform.csrf, line 22, in execute
Module z3c.form.action, line 98, in execute
Module z3c.form.button, line 315, in __call__
Module z3c.form.button, line 170, in __call__
Module plone.app.multilingual.browser.controlpanel, line 57, in handleSave
Module plone.app.multilingual.browser.setup, line 81, in setupSite
Module plone.app.multilingual.browser.setup, line 100, in linkTranslations
TypeError: ('Could not adapt', <Richfolder at /scale/en>, <InterfaceClass plone.app.multilingual.interfaces.ITranslationManager>) Are your folders ITranslatable?

```

The code knows nothing about `plone.app.multilingual.interfaces.ITranslatable`. Perhapse there should be a better error message here and/or the documentation on using `plone.app.multilingual.interfaces.ITranslatable` should be improved.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
