### ISSUE TITLE
Translation UI is a disgrace for content editors, too small, should be opened as popup

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.multilingual#327]
The default translation UI is completely unusable for editors. Neither the original content nor the space for the space for the editor are sufficient. The screenshot is self-speaking. As an editor I want to have the available space of the browser window available for working. Nobody needs the portlets slots in this editorial context. Either the portlet slots should be hidden for this view or this view should be opened as overlay or popup in order to consume the maximal available width of the browser.

![screenshot-dev zopyx de-5080-2018 11 27-15-51-42](https://user-images.githubusercontent.com/594239/49089788-96758f80-f25c-11e8-956a-d53558273748.png)

**Comment by jensens** [comment]
fixed in #328
