### ISSUE TITLE
@@create_translation redirecting to (wrong) source language

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.multilingual#329]
Plone 5.1.4, p.a.m 5.2.3

Situation: a migrated site with two language folder `de` and `en`.

For a particular content in `en`, `create_translation` redirects me to an improper language ("en" again in this case). See

https://community.plone.org/t/plone-app-multilingual-original-content-not-showing-up-in-edit-interface/7597/3?u=zopyx

I am debugging

https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/factory.py#L42-L51

It turns out that the traverser walk up from `/scale/en` to the site root `scale` then then exits the while loop because of 

```
(Pdb) parent
<PloneSite at /scale>
(Pdb) IPloneSiteRoot.providedBy(parent)
True
(Pdb) ILanguageRootFolder.providedBy(parent)
False
```
So it looks as if the Plone site root does not provide `ILanguageRootFolder`?!

But shouldn't this happen as part of the p.a.m. installation?

**Comment by petschki** [comment]
The `ILanguageRootFolders` are `de` or `en` not the Plone Site itself. So I think the problem here is, that your `en` folders translation does not reference correctly to the `de` folder ... `ITranslationManager('en').get_translation()` should return `de` IMO ...

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
