### ISSUE TITLE
TypeError enabling languages in controlpanel

### ISSUE THREAD

**Issue by wkbkhard** [plone/plone.app.multilingual#337]
**Versions:**
Plone 5.1.5 (5115)
Zope 2.13.27
Python 2.7.15rc1
plone.app.multilingual 5.2.3

**Traceback:**
ERROR Zope.SiteErrorLog 1554797967.150.142960092785 http://localhost:8092/Plone/@@language-controlpanel
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 22, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.app.multilingual.browser.controlpanel, line 57, in handleSave
  Module plone.app.multilingual.browser.setup, line 83, in setupSite
  Module plone.app.multilingual.browser.setup, line 269, in setupLanguageSwitcher
TypeError: can only concatenate list (not "tuple") to list

**Steps to reproduce:**
- Installed plone.app.multilingual 5.2.3
- go to @@language-controlpanel
- add new language to available languages in the selection widget
- press save

**Other information:**
- Work around for me: Added the new available languages directly in portal_registry
- the problem in line 269 seems to be that site.view_methods is a list and the code tries to add a tuple (('language-switcher', )) to it < but i am not exactly sure what this code should do at this point
- on other Plone Sites (some in production already, but version 5.1.2) this problem doesn't persist

**Comment by mliebischer** [comment]
I got the same error after uninstalling PAM 5.2.3 and try to reinstall it.

> Traceback (innermost last):
> 
> Module ZPublisher.Publish, line 138, in publish
> Module ZPublisher.mapply, line 77, in mapply
> Module ZPublisher.Publish, line 48, in call_object
> Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 689, in __call__
> Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 454, in install_product
> Module Products.GenericSetup.tool, line 388, in runAllImportStepsFromProfile
> __traceback_info__: profile-plone.app.multilingual:default
> Module Products.GenericSetup.tool, line 1478, in _runImportStepsFromContext
> Module Products.GenericSetup.tool, line 1325, in _doRunHandler
> Module plone.app.multilingual.setuphandlers, line 36, in init_pam
> Module plone.app.multilingual.browser.setup, line 83, in setupSite
> Module plone.app.multilingual.browser.setup, line 269, in setupLanguageSwitcher
> TypeError: can only concatenate list (not "tuple") to list

Seems like the setup handler of PAM tries to a add new entry to `site.view_methods` but as @wkbkhard already mentioned the code expects it to be a `tuple`, see:
https://github.com/plone/plone.app.multilingual/blob/f3a9ff4743719066efe57dd88c38c464e77d7c5e/src/plone/app/multilingual/browser/setup.py#L269

After uninstalling PAM the `site.view_methods` becomes a `list`, see
https://github.com/plone/plone.app.multilingual/blob/f3a9ff4743719066efe57dd88c38c464e77d7c5e/src/plone/app/multilingual/setuphandlers.py#L94

**Possible solution:**
Looks like it should always be threaten as a `tuple`.  Something like the following

*setup:*
`methods = tuple(site.view_methods)`

*uninstall:*
`site.view_methods = tuple([m for m in methods if m != 'language-switcher'])`

should do it.

**Work around:** 
Go to `ZMI` -> `portal_types` -> `Plone Site` and re-save the settings. Afterwards the variable becomes a `tuple` again and the setup should run fine.

**Comment by erral** [comment]
@mliebischer please review this PR https://github.com/plone/plone.app.multilingual/pull/341
