### ISSUE TITLE
Avoid permanently caching first language negotiation

### ISSUE THREAD

**Issue by laulaz** [plone/plone.app.multilingual#347]
When you first arrive on /, p.a.m redirects to /en (for example) with a 301 response.
This response is cached by the browser.
If you select a language (via the language selector), lets say "fr", you can browse the site in this language. But as soon as you return to /, the cached response redirects you to the first language (/en in this example).

**Comment by erral** [comment]
Closed in https://github.com/plone/plone.app.multilingual/pull/348
