### ISSUE TITLE
Branch 2.x asks for archetypes.multilingual<3.0,>=2.0.1dev, which doesn't exist.

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.app.multilingual#352]
https://github.com/plone/plone.app.multilingual/blob/2.x/setup.py#L46

Based on https://pypi.org/project/archetypes.multilingual/#history, the only possibility is 2.0.

![Seleção_172](https://user-images.githubusercontent.com/8203476/58186970-410ac000-7c8c-11e9-85a4-3d27c3f6a2ab.png)

Suggestion:

- Change the dependency to 2.0;
- Release a 2.0.1 version in archetypes.multilingual, since there's a branch in https://github.com/plone/archetypes.multilingual/tree/2.x

@mauritsvanrees I'm mentioning you since you we're the last one commiting to archetypes.multilingual.

**Comment by mauritsvanrees** [comment]
Well spotted. The 2.x branch is not used in any Plone coredev branches, so changes may linger unnoticed.

I have released a new version. I named it 2.1.0, because the changes sounded like more than simple bug fixes, and the previous 2.0 release was from four years ago.
