### ISSUE TITLE
Is there any limitation when a content-type has a custom workflow?

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.app.multilingual#353]
I'm using plone.app.multilingual 2.0.4 in a Plone 4 installation, trying to setup with a content type from [collective.polls](https://github.com/collective/collective.polls).

When I try to translate a content, I get an `Unauthorized` exception (even being logged as Manager):

![Seleção_174](https://user-images.githubusercontent.com/8203476/58808135-c88ef200-85ef-11e9-8abc-d864a9317045.png)

In a nutshell, this happens if I try to add `/babel_view` to a content that I would like to translate.

Checking the `error_log`, this is the traceback:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 623, in traverse
  Module ZPublisher.HTTPResponse, line 756, in unauthorized
Unauthorized: You are not authorized to access this resource.
Username and password are not correct.
```
https://github.com/zopefoundation/Zope/blob/2.13.28/src/ZPublisher/Publish.py#L127
https://github.com/zopefoundation/Zope/blob/2.13.28/src/ZPublisher/BaseRequest.py#L622 (Here, `user` is `None` and `self.roles` comes as `()`. Doing `from AccessControl import getSecurityManager; print(getSecurityManager()._context.user)` gives `Anonymous User` even if I'm logged as `admin:admin` with `Manager` role)
https://github.com/zopefoundation/Zope/blob/2.13.28/src/ZPublisher/HTTPResponse.py#L756

(Similar errors are hard to find, like https://mail.zope.org/pipermail/zope/2004-August/152222.html)

I checked the poll content-type workflow and it's a custom one:

https://github.com/collective/collective.polls/blob/68c3065208048bc0195dab017bcb5311bbc24ec4/src/collective/polls/profiles/default/workflows/poll_workflow/definition.xml

For the sake of testing, I changed it's workflow to `(Default)` and the error was gone.

What should I actually do to make it possible to translate a content-type with a custom workflow? Is this a known limitation or am I missing a configuration somewhere?

The same error happens with a Plone 5.2 installation. Use this simple buildout:

```cfg
[buildout]
parts = instance
extends =
    https://dist.plone.org/release/5.2-latest/versions.cfg
versions = versions

[instance]
recipe = plone.recipe.zope2instance
user = admin:admin
eggs =
    Plone
    Pillow
    collective.polls==2.0b1
    plone.app.multilingual
```

**Comment by idgserpro** [comment]
@erral do you have any idea about what's going on here? Specially why on https://github.com/zopefoundation/Zope/blob/2.13.28/src/ZPublisher/BaseRequest.py#L622 `user` is `None` and self.roles comes as `()` just by adding `babel_view` to the object with a custom workflow?

**Comment by idgserpro** [comment]
I'm mentioning @witsch and @datakurre since you worked with some stuff that may be related to this issue:

https://github.com/plone/plone.app.multilingual/issues/120#issuecomment-74670322
https://github.com/plone/plone.app.multilingual/pull/154
https://github.com/plone/plone.app.multilingual/pull/351

**Comment by datakurre** [comment]
Have you tried with verbose-security to get more exact error message?

Unauthorized error with admin is possible, because the initial traverse happens always before authentication (for performance reasons).

**Comment by idgserpro** [comment]
@datakurre Even with `verbose-security = on` the traceback is the same from the first post:

```
2019-09-02 17:23:13 ERROR Zope.SiteErrorLog 1567455793.020.298770638858 http://localhost:8080/Plone/pt-br/enquete/babel_view
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 623, in traverse
  Module ZPublisher.HTTPResponse, line 756, in unauthorized
Unauthorized: You are not authorized to access this resource.
No Authorization header found.
```

**Comment by idgserpro** [comment]
@datakurre Let's try to simplify this debugging: check the `babel_view`.

`babel_view` itself asks for a `cmf.ModifyPortalContent`:

https://github.com/plone/plone.app.multilingual/blob/1dd5574f102389476711ec02b188af02382d9e4a/src/plone/app/multilingual/browser/configure.zcml#L246

The state mentioned in this issue that gave the "Insufficient permissions" of the content-type doesn't have this permission:

https://github.com/collective/collective.polls/blob/d4367837e0779e70eeacec446123963e991548ca/src/collective/polls/profiles/default/workflows/poll_workflow/definition.xml#L34

Indeed, now adding this permission now it works.

But now I'm starting to think: if `cmf.ModifyPortalContent` is needed to add a translation when you select "Create" and even for `babel_view`, shouldn't this be checked as well before rendering the `Translate` menu?

https://github.com/plone/plone.app.multilingual/blob/d453a31208ac920a04f57e0a8302346394c3a7f6/src/plone/app/multilingual/browser/menu.py#L513

Or... should we really be checking for this permission in the first place? Shouldn't it just be `plone.app.multilingual.ManageTranslations` (added to multiple roles in https://github.com/plone/plone.app.multilingual/blob/2ffd0787641e26fcd3bf3036e020b327252897b5/src/plone/app/multilingual/profiles/default/rolemap.xml#L4) since you can have multiple content-types with multiple workflow situations?

**Comment by idgserpro** [comment]
What I still couldn't debug is why, logged as Manager, I can edit the object but can't use a `babel_view` giving "Insufficient Privileges", having no `Modify portal content` in that workflow. If I don't have `Modify portal content` in that context, why am I able to edit the object in the first place?

**Comment by datakurre** [comment]
@idgserpro You most probably have caught something here.

In practice, adding translation needs the same permissions as "contributor role" is expected to have at the location of the future translation. "cmf.ModifyPortalContent" is not probably always enough, and content types can even have their own permissions.

For me it seems now that this has been a compromise and checking "cmf.ModifyPortalContent" has just been a good guess for enough permissions for the translation.

Checking in translation menu would be best, but that could be expensive, because it would require traverse per translatable language.

Using  `Manage Translations` permissions would be really hard, because it's probably beyond possible to make it replace "Add portal content" (and maybe also "Modify portal content") for translations.

**Comment by idgserpro** [comment]
> Checking in translation menu would be best, but that could be expensive, because it would require traverse per translatable language.

Would really be expensive to add (just an example):

```
        from Products.CMFCore.permissions import ModifyPortalContent
        if not sm.checkPermission(ModifyPortalContent, self.context):
            return False
```

To the end of https://github.com/plone/plone.app.multilingual/blob/d453a31208ac920a04f57e0a8302346394c3a7f6/src/plone/app/multilingual/browser/menu.py#L513,L532?

**Comment by datakurre** [comment]
@idgserpro But the permission for translating to language X is not required at the context, but at the eventual location of the translation.

**Comment by idgserpro** [comment]
I need `cmf.ModifyPortalContent` to use `babel_view` if I'm in a content type view, but this permission is not checked when rendering the `Translate` menu. I think it should. It's just an usability improvement.

**Comment by datakurre** [comment]
But it should be possible translate content to the another language even when you don't have permissions to modify it. Contracting translators should only need content management permissions for the translations they are responsible of. They should not necessarily need management permissions for the translations they are not responsible of. Still you should see translation menu everywhere. (And yes, in this scenario Manage Translations would still give too much permissions for the translators, because they would be able to disconnect translations they are not responsible of.)

**Comment by idgserpro** [comment]
> But it should be possible translate content to the another language even when you don't have permissions to modify it

I can understand the motivation above, but can't see how it would work in the current implementation since you still need `Modify portal content` permission to translate.

To acomplish what you said, it would be possible to contractors to have permission only in the translations folders, and link the translations instead of trying to translate them in folders they don't have permission.

**Comment by datakurre** [comment]
Yes, for me it sounds like a bug if translation really requires Modify portal content for the original version.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
