### ISSUE TITLE
Error when adding new languages when you have content in the 'assets' folder

### ISSUE THREAD

**Issue by erral** [plone/plone.app.multilingual#358]
Steps to reproduce:

1. Create a Plone site, add some languages and enable p.a.multilingual.
2. Add some content in the 'assets' folder
3. Go to the Language Control Panel and add another language.

The traceback is the following:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 22, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.app.multilingual.browser.controlpanel, line 57, in handleSave
  Module plone.app.multilingual.browser.setup, line 79, in setupSite
  Module plone.app.multilingual.browser.setup, line 152, in setUpLanguage
  Module Products.CMFPlone.utils, line 357, in _createObjectByType
  Module Products.CMFCore.TypesTool, line 570, in _constructInstance
  Module Products.BTreeFolder2.BTreeFolder2, line 444, in _setObject
  Module zope.event, line 32, in notify
  Module zope.component.event, line 27, in dispatch
  Module zope.component._api, line 124, in subscribers
  Module zope.interface.registry, line 442, in subscribers
  Module zope.interface.adapter, line 607, in subscribers
  Module zope.component.event, line 36, in objectEventNotify
  Module zope.component._api, line 124, in subscribers
  Module zope.interface.registry, line 442, in subscribers
  Module zope.interface.adapter, line 607, in subscribers
  Module OFS.subscribers, line 103, in dispatchObjectWillBeMovedEvent
  Module zope.container.contained, line 163, in dispatchToSublocations
  Module zope.component._api, line 127, in handle
  Module zope.interface.registry, line 442, in subscribers
  Module zope.interface.adapter, line 607, in subscribers
  Module plone.app.multilingual.subscriber, line 96, in unindex_language_independent
  Module OFS.Traversable, line 195, in unrestrictedTraverse
AttributeError: getPhysicalRoot
```
This happens on http://demo-latest-py3.plone.org

Versions:
Plone 5.2.1.dev0 (5208)
CMF 2.4.0
Zope 4.1.1
Python 3.6.3 (default, Oct 9 2017, 22:37:08) [GCC 4.8.4]
PIL 6.1.0 (Pillow)
WSGI: Enabled
Servidor: waitress 1.3.0

And also on http://demo-latest-py2.plone.org/ 
Plone 5.2.1.dev0 (5208)
CMF 2.4.0
Zope 4.1.1
Python 2.7.14 (default, Oct 9 2017, 22:27:46) [GCC 4.8.4]
PIL 6.1.0 (Pillow)
WSGI: Enabled
Zerbitzaria: waitress 1.3.0

And also on http://demo.plone.org
Plone 5.2.0 (5207)
CMF 2.4.0
Zope 4.1.1
Python 3.7.2 (default, Mar 11 2019, 14:41:38) [GCC 5.4.0 20160609]
PIL 6.1.0 (Pillow)
WSGI: Enabled
Zerbitzaria: waitress 1.3.0

**Comment by erral** [comment]
In all three cases the used version is plone.app.multilingual = 5.3.5

**Comment by erral** [comment]
I have also checked this in Plone 5.1.5 and plone.app.multilingual 5.2.3 and **it does not happen**.

Plone 5.1.5 (5115)
CMF 2.2.12
Zope 2.13.27
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
PIL 5.2.0 (Pillow)

**Comment by petschki** [comment]
Just got bitten by this too ... the main difference from version 5.2.x to 5.3.x is, that the event `IObjectWillBeMovedEvent` (and therefore the method `unindex_language_independent`) isn't fired at all in 5.2.x ... which is the correct behavior from my point of view ... just investigating why 5.3.x fires that event in case of adding a new language ... @mauritsvanrees maybe some ideas?

**Comment by mauritsvanrees** [comment]
It is an `IObjectWillBeMovedEvent`, but more specifically an `IObjectWillBeAddedEvent`. The `reindex_language_independent` subscriber is called shortly afterwards.
It may help to have an extra check if `unindex_language_independent` like this:

```
if IObjectWillBeAddedEvent.providedBy(event):
    return
```

That would prevent an unindex followed by a reindex.
Untested though.

Anyway, I merged your PR as it fixes the immediate problem.
