### ISSUE TITLE
portlet-cols on add and edit view not the same

### ISSUE THREAD

**Issue by iham** [plone/plone.app.multilingual#373]
while on edit, the left and right portlet column is disabled.
-> https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/browser/edit.py#L65-L66

on the add view, those are not hidden.
https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/browser/add.py#L128

why?
is there any particular reason to make them act differently?

i expected the same habit on both views and managed to "hot fix" that for my project, by overriding dexterity_edit.pt
```xml
<div class='row' id='babel-edit'
      xmlns="http://www.w3.org/1999/xhtml"
      xml:lang="en"
      lang="en"
      xmlns:tal="http://xml.zope.org/namespaces/tal"
      xmlns:metal="http://xml.zope.org/namespaces/metal"
      xmlns:i18n="http://xml.zope.org/namespaces/i18n"
      i18n:domain="plone"
      tal:define="pamutils context/@@babel_utils;
                  disable_column_one python:request.set('disable_plone.leftcolumn',1);
                  disable_column_two python:request.set('disable_plone.rightcolumn',1);">
```
see last two lines here

as using the full width seems convenient, it might be cool to have that in both forms - add AND edit

**Comment by iham** [comment]
i might sound nagging ...

can someone please add some opinion on that topic?
@agitator 
@santonelli
@jensens 
@pbauer

**Comment by erral** [comment]
Yes, that would be fine.

Can you add a PR?

**Comment by iham** [comment]
did it on add.py render method instead of the template

**Comment by santonelli** [comment]
+1

Same behavior on add/edit sounds good.
