### ISSUE TITLE
Update markup of templates to Bootstrap

### ISSUE THREAD

**Issue by santonelli** [plone/plone.app.multilingual#379]
Due to #2967 we have to update the markup of the templates listed below. 

- [x] plone.app.multilingual.browser.templates.add-form-is-translation.pt
- [x] plone.app.multilingual.browser.templates.alternate-languages.pt
- [x] plone.app.multilingual.browser.templates.cleanup.pt (not done old LP migration)
- [x] plone.app.multilingual.browser.templates.cleanup_results.pt (not done old LP migration)
- [x] plone.app.multilingual.browser.templates.controlpanel.pt
- [x] plone.app.multilingual.browser.templates.dexterity_edit.pt
- [x] plone.app.multilingual.browser.templates.disconnect_translation.pt
- [x] plone.app.multilingual.browser.templates.dx_babel_view.pt
- [x] plone.app.multilingual.browser.templates.languages-notice.pt
- [x] plone.app.multilingual.browser.templates.languageselector.pt
- [x] plone.app.multilingual.browser.templates.migration.pt (not done old LP migration)
- [x] plone.app.multilingual.browser.templates.migrator-results.pt (not done old LP migration)
- [x] plone.app.multilingual.browser.templates.mmap.pt
- [x] plone.app.multilingual.browser.templates.modify_translations.pt
- [x] plone.app.multilingual.browser.templates.not_translated_yet.pt
- [x] plone.app.multilingual.browser.templates.reindex-results.pt (not done old LP migration)
- [x] plone.app.multilingual.browser.templates.relocate-results.pt (not done old LP migration)

Feel free to add missing templates here.

**Comment by agitator** [comment]
@Gomez what's the status on this?

**Comment by Gomez** [comment]
@agitator WIP. Still on it. Will update the todos here as soon as i work on it again.

**Comment by Gomez** [comment]
Improved some templates, some other are only for Linguaplone migration -> havent touched.

Needs a review from bootstrap pro.
