### ISSUE TITLE
Better folder preset for connecting translations

### ISSUE THREAD

**Issue by gogobd** [plone/plone.app.multilingual#445]
When you click "connect translations" on an object you will be presented with a dialog to choose the content to use for the connection. Unfortunately the pre-selection is very poor, you would usually see the Root folder of your Site.

The new behavior is as follows:
Check if there is a translation of the container (parent) of the content you want to connect in the target language. If so, use this the preset. If not go "up" one parent and repeat. This would give you the Language Root Folder in the "worst case" when there were no translations, but it will also give you the "expected" folder if it has already been translated.

**Comment by jensens** [comment]
#446 got merged.
