### ISSUE TITLE
new 7 release?

### ISSUE THREAD

**Issue by krissik** [plone/plone.app.multilingual#449]
We get hit by this https://github.com/plone/plone.app.multilingual/issues/437

but it is fixed only in version 8. Is a new 7 release planed?

**Comment by davisagli** [comment]
@gogobd Your PR https://github.com/plone/plone.app.multilingual/pull/438 was for the master branch of plone.app.multilingual which is only used for Plone 6.1. Do you want to also backport it to the 7.x branch?

**Comment by davisagli** [comment]
Fixed in #450
