### ISSUE TITLE
page not found error in multilingual repository

### ISSUE THREAD

**Issue by SophiaLi20** [plone/plone.app.multilingual#469]
In read-me section page not found error has been shown when you see the source code and try to click on **Process for Plone core's development** and that redirects you on  [Access](https://6.docs.plone.org/develop/coredev/docs/index.html)

**Comment by davisagli** [comment]
Fixed in https://github.com/plone/plone.app.multilingual/commit/7aedd0ab71d3edf5d1fb4cb86b9f611d428ed76b
