### ISSUE TITLE
translating  default view of a container -> usability issue

### ISSUE THREAD

**Issue by fgrcon** [plone/plone.app.multilingual#52]
refers to plone 4.3, pam1.1 dev
- install a new plone site with pam
- e.g. go  to the News tab ( installed by default)
  translate ....
   --> \* you get a new collection directly under  the language folder
        \* you need to translate the news folder and move the collection into this folder manually
## proposals

One solution might be similarly to follow  how it works with the edit tab:

Info
    You are translating the default view of a container. If you wanted to translate the container itself (what you should do first), go here. 

Much more convenient would be translating container and default-view document automatically in one step (including the query parameters of collections; in this case the language folder part needs to be taken into acount, if there is a path criterion), display settings etc.)

**Comment by fgrcon** [comment]
3 years later:  Still an issue  Plone 5.1  Branch ... / pam 4.x
from user experience point of view:  :-1:

**Comment by dlmueller** [comment]
I am currently evaluating Plone (version 5.0.6rc1) as a possible candidate to substitute the current CMS at our university. Support for multilingual content is one of the main requirements and so far I am very pleased with `plone.app.multilingual`. Regarding the current handling of Dexterity Collection type, i.e. the manual  duplication of the query parameter could be improved.

One solution could by a "copy field value from source" option. This would ease the initial translation, but still involves the risk that modified query parameters in the default language content might be forgotten in the translated content.

So another solution could be an option  "bind field value between source and translation". Whenever the query parameters of one of the corresponding content elements will be modified there could be the option to compare the bound field values (similar to the multilingual translation map) and let the content editors decide which of the copies is the right one.

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue
