### ISSUE TITLE
Language selector should be adaptable to have a different behavior if pam is installed

### ISSUE THREAD

**Issue by bloodbare** [plone/plone.app.multilingual#90]
In case p.a.m. is installed the behavior of language selector should be different so we need a new way yo deal with it

**Comment by djowett** [comment]
Is this saying that the language selector doesn't work with p.a.m?... even with v1.x?

**Comment by jensens** [comment]
We don't need a language selector at the type at all, right? IIRC there is some code hiding the selector iirc? Can we close this one or is there some work to do?

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
